# Generated by Django 3.2.25 on 2025-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('bgroup', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Udata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
    ]
