# Generated by Django 3.2.25 on 2025-03-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdata',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
