# Generated by Django 4.1.7 on 2025-03-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_rdata_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdata',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
