# Generated by Django 4.1.7 on 2025-03-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_rdata_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdata',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
